spring.application.name=TESTEINTEGRADO


# Configuração da URL para Banco em Memória
spring.datasource.url=jdbc:h2:mem:testdb;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o Console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate para criar as tabelas automaticamente
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/schema.sql,classpath:db/seed.sql